cd saved_models_29556
python3 extracting_CodeBERT_embeddings.py
bash rsa_script.bash
cd ../saved_models_15000
python3 extracting_CodeBERT_embeddings.py
bash rsa_script.bash
cd ../saved_models_7500
python3 extracting_CodeBERT_embeddings.py
bash rsa_script.bash
cd ../saved_models_3750
python3 extracting_CodeBERT_embeddings.py
bash rsa_script.bash
cd ../saved_models_1875
python3 extracting_CodeBERT_embeddings.py
bash rsa_script.bash
cd ../saved_models_938
python3 extracting_CodeBERT_embeddings.py
bash rsa_script.bash
